module(..., package.seeall)

WIDTH = 800
HEIGHT = 600
INIT_JUMP_HEIGHT = 800
JUMP_HEIGHT = INIT_JUMP_HEIGHT
INIT_MAX_SPEED = 300
MAX_SPEED = INIT_MAX_SPEED
INIT_GRAVITY = 1960
GRAVITY = INIT_GRAVITY
INIT_ACCELERATION = 900
ACCELERATION = INIT_ACCELERATION
INIT_FRICTION = 0.8
FRICTION = INIT_FRICTION
INIT_WALL_JUMP_ANGLE = 58.6
WALL_JUMP_ANGLE = INIT_WALL_JUMP_ANGLE
HASMAP = false
HASCOMPASS = false
SMALLFONT = love.graphics.newFont("AvalonQuest.ttf", 25)
LARGEFONT = love.graphics.newFont("AvalonQuest.ttf", 40)
HUGEFONT = love.graphics.newFont("AvalonQuest.ttf", 75)